addSbtPlugin("ch.epfl.lamp"                      % "sbt-dotty"        % "0.4.6")
addSbtPlugin("ch.epfl.scala"                     % "sbt-bloop"        % "1.4.5")
addSbtPlugin("com.geirsson"                      % "sbt-ci-release"   % "1.5.4")
addSbtPlugin("com.thoughtworks.sbt-api-mappings" % "sbt-api-mappings" % "3.0.0")
addSbtPlugin("io.github.davidgregory084"         % "sbt-tpolecat"     % "0.1.16")
addSbtPlugin("org.scalameta"                     % "sbt-mdoc"         % "2.2.10")
addSbtPlugin("org.scalameta"                     % "sbt-scalafmt"     % "2.4.2")
