addSbtPlugin("com.dwijnand"              % "sbt-dynver"   % "4.0.0")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt" % "2.0.6")
addSbtPlugin("ch.epfl.scala"             % "sbt-bloop"    % "1.3.3")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.8")
addSbtPlugin("org.scalameta"             % "sbt-mdoc"     % "1.3.4")
addSbtPlugin("com.jsuereth"              % "sbt-pgp"      % "2.0.0")
addSbtPlugin("org.xerial.sbt"            % "sbt-sonatype" % "3.8")
